### ISSUE TITLE
solidify the study card requirements for GTM

### ISSUE THREAD

**Issue by knowtheory** [mozilla-ion/ion-core-addon#192] opened 2020-11-20 17:05 UTC
This is a meta/discussion ticket for Study Cards and their requirements.

We have several sets of requirements around study cards: visual design; partner process; ux design.

Based on a conversation the team had in standup, our first goal should be to collate all of the requirements documents and current documentation available for our process.

Please add your questions and links!

**Comment by jcchuang** [comment] 2020-11-20 17:14
Are these requirements part of GTM or not?

**Comment by marniepw** [comment] 2020-11-20 17:28
What do we need for GTM?
What do we need, longer term?

**Comment by hamilton** [comment] 2020-12-03 17:39
Duplicate of #172. Closing.

**Closed by hamilton** 2020-12-03 17:39 UTC
Labels: discussion, effort M
