### ISSUE TITLE
How many times should ion.js bug the user if they are not enrolled?

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#82] opened 2020-10-16 16:58 UTC
There are essentially two entry-points to Ion:

1) installing core add-on (either by installing directly or through landing web page)
2) installing study add-on

(1) opens the enrollment flow on install
(2) opens the landing page if Ion core add-on is not present

If the user is in one of these states and doesn't join Ion, they will have one or more useless extensions installed. Currently (1) only happens on install and (2) happens on every browser startup.

How often do we want to bother users? Do we "give up" at some point and uninstall the add-ons if the user never gets around to joining Ion?

**Comment by Dexterp37** [comment] 2020-11-17 17:01
Issue #171 is a duplicate of this, but slightly different. The other has flagged the UX folks already, closing this one.

**Closed by Dexterp37** 2020-11-17 17:01 UTC
Labels: question
