### ISSUE TITLE
Add ESLint?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-ion/ion-core-addon#118] opened 2020-11-02 18:30 UTC
Fiddled around with it a bit and came up with this.
Currently about 55 errors, but pretty easy to bring it down to 13-17 by fixing a bit of low hanging fruit (re: leaky variables, unreachable code, etc...)

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
    webextensions: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:import/warnings",
  ],
  globals: {
    ChromeUtils: false,
    ExtensionAPI: false,
    // NOTE: These get injected via Rollup.
    __API_ENDPOINT__: false,
    __ION_STUDIES_LIST__: false,
    __ION_WEBSITE_URL__: false,
    __STORE_IMPLEMENTATION__: false,
  },
  overrides: [
    {
      files: "tests/**",
      env: {
        mocha: true,
      },
    },
  ],
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: "module",
  },
  plugins: [
    "import",
  ],
  root: true,
  rules: {
    "no-var": "off", // TODO: "warn",
    "prefer-const": "off", // TODO: "warn",
    "no-unused-vars": [ "error", { vars: "all", args: "none", ignoreRestSiblings: false } ],
  },
};
```

Possibly a dupe of #59

**Comment by Dexterp37** [comment] 2020-11-03 10:59
Thank you for this @pdehaan ! Yes, this looks like a dupe of #59. I closed that one, since this is actively being worked on :)

**Closed** 2020-11-04 11:08 UTC
